# Copies relevant files to the Bitwig directory.

# Create env file
if [[ ! -f ".env" ]]; then
    echo "Please specify the directory to copy files to:"
    read dest
    echo "DESTINATION_FOLDER=$dest" >> .env
    exit
fi

source ./.env
echo "target: '$DESTINATION_FOLDER'"
echo ""
# If there's an issue you may need to escape strings.

set -e

#
# Build and copy all scripts
#

# All scripts that live in src/*
SCRIPTS=(
launchpadx
mpd218
)


buildScripts(){
    echo "$1"
    echo "- Copying"
    CORE_TS_FILES=src/@core/core_*.ts
    DESTINATION=$1

    rm -f "$DESTINATION/core_*.ts" 2> /dev/null
    cp $CORE_TS_FILES "$DESTINATION/"
    
    rm -f "$DESTINATION/tsconfig.json"
    JSON_PRESET=src/@core/tsconfig.json
    cp $JSON_PRESET "$DESTINATION/"

    echo "- Compiling "
    tsc --project "$DESTINATION/"
    echo "- Done"
}


for controlFile in src/*; do
    echo $controlFile
    if [[ "$controlFile" == "src/out" || "$controlFile" == "src/@core" ]]; then
        echo "Skipping $controlFile"
    else 
        buildScripts "$controlFile"
    fi
done


#
# Combine files
#
echo "Begin single file generation"
for controlFile in src/out/*.control.js; do
    echo "generating $controlFile"
    NEW_TARGET="$controlFile.final.js"

    # add all core files to control files
    rm -f $NEW_TARGET

    echo "//" >> $NEW_TARGET
    echo "// THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE MODIFIED BY HAND" >> $NEW_TARGET
    echo "// THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE MODIFIED BY HAND" >> $NEW_TARGET
    echo "// THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE MODIFIED BY HAND" >> $NEW_TARGET
    echo "// THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE MODIFIED BY HAND" >> $NEW_TARGET
    echo "//" >> $NEW_TARGET

    for coreFile in src/out/core_*.js; do        
        echo "- $coreFile done"
        echo "$(cat $coreFile)" >> $NEW_TARGET
    done

    echo "$(cat $controlFile)" >> $NEW_TARGET
    echo "- $controlFile done"
    rm -f $controlFile

    mv $NEW_TARGET $controlFile

  #  cat "$controlFile"
done

#
# Copy all outputs to destination folder
#
echo ""
echo "Copying to $DESTINATION/out"
#rm -rd -f "$DESTINATION_FOLDER/out"
cp -r src/out "$DESTINATION_FOLDER/out"

#
#
#
echo ""
echo "~ ~ FIN ~ ~"